##### Analyses for Bowden and Diehl Paper #####

data <- read.csv("tc_1_14.csv")

data$drop <- ifelse(data$portion==1 & (data$loser==data$entity | data$gainer==data$entity),1,0)
data <- subset(data,drop==0)

library(Zelig)
library(stargazer)

###Table 1 - MIDs
m1 = glm(mid1 ~ agreement + rivals + contlose + conflict, data=data, family=binomial(logit))
summary(m1)
m2 = glm(window5 ~ agreement + rivals + contlose + conflict, data=subset(data, year <= 2003), family=binomial(logit))
summary(m2)
m3 = glm(window10 ~ agreement + rivals + contlose + conflict, data=subset(data,year <= 1998), family=binomial(logit))
summary(m3)
m4 = glm(window20 ~ agreement + rivals + contlose + conflict, data=subset(data, year <= 1988), family=binomial(logit))
summary(m4)

mids <- c("MID within 1 Year","MID within 5 Years","MID within 10 Years","MID within 20 Years")
cov <- c("Agreement","Rivalry","Losing Side's Homeland", "Conflict")
stargazer(m1,m2,m3,m4,title="Logit Models of the Effect of Legalized Territorial Transfers on Territorial MIDs",style="apsr",dep.var.labels=mids,covariate.labels=cov)

###Table 2 - claims
c1 = glm((claim1==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data,year<=2001), family=binomial(logit))
summary(c1)
c2 = glm((outstanding.claim.5==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data, year <= 1996), family=binomial(logit))
summary(c2)
c3 = glm((outstanding.claim.10==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data,year <= 1991), family=binomial(logit))
summary(c3)
c4 = glm((outstanding.claim.20==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data, year <= 1981), family=binomial(logit))
summary(c4)

claims <- c("Claim within 1 Year","Claim within 5 Years","Claim within 10 Years","Claim within 20 Years")
stargazer(c1,c2,c3,c4,title="Logit Models of the Effect of Legalized Territorial Transfers on Outstanding Territorial Claims (New or Continuing)",style="apsr",dep.var.labels=claims,covariate.labels=cov)

###Tables 3 and 4 - Agreement x Conflict
data$agreement <- as.factor(data$agreement)
data$conflict <- as.factor(data$conflict)
data$rivals <- as.factor(data$rivals)

i1 = glm(mid1 ~ agreement*conflict + rivals + contlose, data=data, family=binomial(logit))
summary(i1)
i2 = glm(window5 ~ agreement*conflict + rivals + contlose, data=subset(data,year <= 2003), family=binomial(logit))
summary(i2)
i3 = glm(window10 ~ agreement*conflict + rivals + contlose, data=subset(data,year <= 1998), family=binomial(logit))
summary(i3)
i4 = glm(window20 ~ agreement*conflict + rivals + contlose, data=subset(data,year <= 1988), family=binomial(logit))
summary(i4)
i5 = glm((claim1==1 & partial==1) ~ agreement*conflict + rivals + contlose, data=subset(data,year<=2001), family=binomial(logit))
summary(i5)
i6 = glm((outstanding.claim.5==1 & partial==1) ~ agreement*conflict + rivals + contlose, data=subset(data,year<=1996), family=binomial(logit))
summary(i6)
i7 = glm((outstanding.claim.10==1 & partial==1) ~ agreement*conflict + rivals + contlose, data=subset(data,year<=1991), family=binomial(logit))
i8 = glm((outstanding.claim.20==1 & partial==1) ~ agreement*conflict + rivals + contlose, data=subset(data,year<=1981), family=binomial(logit))

interactions <- c("Agreement","Conflict","Rivals","Losing Side's Homeland","Agreement X Conflict")
int.d <- c("MID within 1 Year","MID within 5 Years","MID within 10 Years","MID within 20 Years")
stargazer(i1,i2,i3,i4,title="Interactions of Conflict and Agreement",style="apsr",dep.var.labels=int.d,covariate.labels=interactions)
int.c <- c("Claim within 1 Year","Claim with 5 Years","Claim within 10 Years","Claim within 20 Years")
stargazer(i5,i6,i7,i8,title="Interactions of Conflict and Agreement (Continued)",style="apsr",dep.var.labels=int.c,covariate.labels=interactions)

###Tables 5 and 6 - Rivalry x Agreement
k1 <- glm(mid1 ~ agreement*rivals + contlose + conflict, data=data, family=binomial(logit))
summary(k1)
k2 = glm(window5 ~ agreement*rivals + contlose + conflict, data=subset(data,year<=2003), family=binomial(logit))
summary(k2)
k3 = glm(window10 ~ agreement*rivals + contlose + conflict, data=subset(data,year<=1998), family=binomial(logit))
summary(k3)
k4 = glm(window20 ~ agreement*rivals + contlose + conflict, data=subset(data,year<=1988), family=binomial(logit))
summary(k4)
k5 = glm((claim1==1 & partial==1) ~ agreement*rivals + contlose + conflict, data=subset(data,year<=2001), family=binomial(logit))
summary(k5)
k6 = glm((outstanding.claim.5==1 & partial==1) ~ agreement*rivals + contlose + conflict, data=subset(data,year<=1996), family=binomial(logit))
k7 = glm((outstanding.claim.10==1 & partial==1) ~ agreement*rivals + contlose + conflict, data=subset(data,year<=1991), family=binomial(logit))
k8 = glm((outstanding.claim.20==1 & partial==1) ~ agreement*rivals + contlose + conflict, data=subset(data,year<=1981), family=binomial(logit))

riv.interactions <- c("Agreement","Rivals","Losing Side's Homeland","Conflict","Agreement X Rivals")
stargazer(k3,k4,title="Interactions of Rivalry and Agreement",style="apsr",dep.var.labels=c("MID within 10 Years","MID within 20 Years"),covariate.labels=riv.interactions)
stargazer(k5,k6,k7,k8,title="Interactions of Rivalry and Agreement (Continued)",style="apsr",dep.var.labels=int.c,covariate.labels=riv.interactions)

###Figure 1: Agreement x Conflict Marginals
library(effects)

eff.i1 <- effect("agreement*conflict",i1)
eff.i2 <- effect("agreement*conflict",i2)
eff.i3 <- effect("agreement*conflict",i3)
eff.i4 <- effect("agreement*conflict",i4)
eff.i5 <- effect("agreement*conflict",i5)
eff.i6 <- effect("agreement*conflict",i6)
eff.i7 <- effect("agreement*conflict",i7)
eff.i8 <- effect("agreement*conflict",i8)

plot(eff.i1,xlab="Agreement",ylab="",main="MID within 1 Year",style="stacked",rug=F,key.args=list(space="right"),row=1,col=1,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i2,xlab="Agreement",ylab="",main="MID within 5 Years",style="stacked",rug=F,key.args=list(space="right"),row=1,col=2,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i3,xlab="Agreement",ylab="",main="MID within 10 Years",style="stacked",rug=F,key.args=list(space="right"),row=1,col=3,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i4,xlab="Agreement",ylab="",main="MID within 20 Years",style="stacked",rug=F,key.args=list(space="right"),row=1,col=4,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i5,xlab="Agreement",ylab="",main="Claim within 1 Year",style="stacked",rug=F,key.args=list(space="right"),row=2,col=1,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i6,xlab="Agreement",ylab="",main="Claim within 5 Years",style="stacked",rug=F,key.args=list(space="right"),row=2,col=2,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i7,xlab="Agreement",ylab="",main="Claim within 10 Years",style="stacked",rug=F,key.args=list(space="right"),row=2,col=3,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.i8,xlab="Agreement",ylab="",main="Claim within 20 Years",style="stacked",rug=F,key.args=list(space="right"),row=2,col=4,nrow=2,ncol=4,par.settings = list(strip.background=list(col="lightgrey")))

###Figure 2: Agreement x Rivalry Marginals
eff.k1 <- effect("agreement*rivals",k1)
eff.k2 <- effect("agreement*rivals",k2)
eff.k3 <- effect("agreement*rivals",k3)
eff.k4 <- effect("agreement*rivals",k4)
eff.k5 <- effect("agreement*rivals",k5)
eff.k6 <- effect("agreement*rivals",k6)
eff.k7 <- effect("agreement*rivals",k7)
eff.k8 <- effect("agreement*rivals",k8)

plot(eff.k3,xlab="Agreement",ylab="",main="MID within 10 Years",style="stacked",rug=F,key.args=list(space="right"),row=1,col=3,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.k4,xlab="Agreement",ylab="",main="MID within 20 Years",style="stacked",rug=F,key.args=list(space="right"),row=1,col=4,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.k5,xlab="Agreement",ylab="",main="Claim within 1 Year",style="stacked",rug=F,key.args=list(space="right"),row=2,col=1,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.k6,xlab="Agreement",ylab="",main="Claim within 5 Years",style="stacked",rug=F,key.args=list(space="right"),row=2,col=2,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.k7,xlab="Agreement",ylab="",main="Claim within 10 Years",style="stacked",rug=F,key.args=list(space="right"),row=2,col=3,nrow=2,ncol=4,more=TRUE,par.settings = list(strip.background=list(col="lightgrey")))
plot(eff.k8,xlab="Agreement",ylab="",main="Claim within 20 Years",style="stacked",rug=F,key.args=list(space="right"),row=2,col=4,nrow=2,ncol=4,par.settings = list(strip.background=list(col="lightgrey")))

###Table 7: Pred Prob for Agreement
z1 = zelig(mid1~agreement+contlose+conflict+rivals,data=data,model="logit")
x0 = setx(z1,agreement=0,contlose=1,conflict=0,rivals=0)
s0 = sim(z1,x=x0)
summary(s0)
x1 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=0)
s1 = sim(z1,x=x1)
summary(s1)
z2 = zelig(window5~agreement+contlose+conflict+rivals,data=subset(data,year<=2003),model="logit")
summary(z2)
x3 = setx(z2,agreement=0,contlose=1,conflict=0,rivals=0)
s3 = sim(z2,x=x3)
summary(s3)
x4 = setx(z2,agreement=1,contlose=1,conflict=0,rivals=0)
s4 = sim(z2,x=x4)
summary(s4)
z3 = zelig(window10~agreement+contlose+conflict+rivals,data=subset(data,year<=1998),model="logit")
x5 = setx(z3,agreement=0,contlose=1,conflict=0,rivals=0)
s5 = sim(z3,x=x5)
summary(s5)
x6 = setx(z3,agreement=1,contlose=1,conflict=0,rivals=0)
s6 = sim(z3,x=x6)
summary(s6)
z4 = zelig(window20~agreement+contlose+conflict+rivals,data=subset(data,year<=1988),model="logit")
x7 = setx(z4,agreement=0,contlose=1,conflict=0,rivals=0)
s7 = sim(z4,x=x7)
summary(s7)
x8 = setx(z4,agreement=1,contlose=1,conflict=0,rivals=0)
s8 = sim(z4,x=x8)
summary(s8)

###Table 8: Pred Prob Rivalry
x0.5 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=0)
x1.5 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=1)
r0 = sim(z1,x=x0.5)
summary(r0)
r1 = sim(z1,x=x1.5)
summary(r1)
x2.5 = setx(z2,agreement=1,contlose=1,conflict=0,rivals=0)
x3.5 = setx(z2,agreement=1,contlose=1,conflict=0,rivals=1)
r2 = sim(z2,x=x2.5)
summary(r2)
r3 = sim(z2,x=x3.5)
summary(r3)
x4.5 = setx(z3,agreement=1,contlose=1,conflict=0,rivals=0)
x5.5 = setx(z3,agreement=1,contlose=1,conflict=0,rivals=1)
r4 = sim(z3,x=x4.5)
summary(r4)
r5 = sim(z3,x=x5.5)
summary(r5)
x6.5 = setx(z4,agreement=1,contlose=1,conflict=0,rivals=0)
x7.5 = setx(z4,agreement=1,contlose=1,conflict=0,rivals=1)
r6 = sim(z4,x=x6.5)
summary(r6)
r7 = sim(z4,x=x7.5)
summary(s7)

##### Appendix #####

###Tables 9 and 10: Predicting Agreement
a1 <- glm(agreement~rivals,data=data,family=binomial(logit))
summary(a1)
a2 <- glm(agreement~joint.dem,data=data,family=binomial(logit))
summary(a2)
a3 <- glm(agreement~contlose,data=data,family=binomial(logit))
summary(a3)
a4 <- glm(agreement~caprat,data=data,family=binomial(logit))
summary(a4)
a5 <- glm(agreement~log(pop+1),data=data,family=binomial(logit))
summary(a5)
a6 <- glm(agreement~log(area),data=data,family=binomial(logit))
summary(a6)
a7 <- glm(agreement~rivals+joint.dem,data=data,family=binomial(logit))
summary(a7)
a8 <- glm(agreement~rivals+joint.dem+contlose,data=data,family=binomial(logit))
summary(a8)
a9 <- glm(agreement~rivals+joint.dem+contlose+caprat,data=data,family=binomial(logit))
summary(a9)
a10 <- glm(agreement~rivals+joint.dem+contlose+caprat+log(pop+1),data=data,family=binomial(logit))
summary(a10)
a11 <- glm(agreement~rivals+joint.dem+contlose+caprat+log(pop+1)+log(area),data=data,family=binomial(logit))
summary(a11)
stargazer(a1,a2,a3,a4,a5,a6,covariate.labels=c("Rivalry","Joint Democracy","Losing Side's Homeland","Capability Ratio","Logged Population","Logged Area"),title="Predictors of Agreement",dep.var.labels="Agreement",style="apsr")
stargazer(a7,a8,a9,a10,a11,covariate.labels=c("Rivalry","Joint Democracy","Losing Side's Homeland","Capability Ratio","Logged Population","Logged Area"),title="Predictors of Agreement (Continued)",dep.var.labels="Agreement",style="apsr")

###Table 11: Pre- and Post-WWI MIDs
t1 = glm(mid1 ~ rivals + contlose + conflict, data=subset(data,year<1919), family=binomial(logit))
summary(t1)
t2 = glm(mid1 ~ agreement + rivals + conflict, data=subset(data,year>=1919),family=binomial(logit))
summary(t2) # contlose a perfect predictor or something
t3 = glm(window5 ~ agreement + rivals + contlose + conflict, data=subset(data, year < 1919), family=binomial(logit))
summary(t3)
t4 = glm(window5 ~ agreement + rivals + contlose + conflict, data=subset(data, year >= 1919 & year<=2003), family=binomial(logit))
summary(t4)
t5 = glm(window10 ~ agreement + rivals + contlose + conflict, data=subset(data,year < 1919), family=binomial(logit))
summary(t5)
t6 = glm(window10 ~ agreement + rivals + contlose + conflict, data=subset(data,year >= 1919 & year<=1998), family=binomial(logit))
summary(t6)
t7 = glm(window20 ~ agreement + rivals + contlose + conflict, data=subset(data, year < 1919), family=binomial(logit))
summary(t7)
t8 = glm(window20 ~ agreement + rivals + contlose + conflict, data=subset(data, year >= 1919 & year<=1988), family=binomial(logit))
summary(t8)

labels <- c("pre-WWI","post-WWI","pre-WWI","post-WWI","pre-WWI","post-WWI","pre-WWI","post-WWI")
cov <- c("Agreement","Rivalry","Losing Side's Homeland", "Conflict")
stargazer(t1,t2,t3,t4,t5,t6,t7,t8,title="Logit Models of the Effect of Legalized Territorial Transfers on Territorial MIDs",style="apsr",dep.var.labels=mids,covariate.labels=cov,column.labels=labels)

###Table 12:Pre- and Post-WWI - claims
ct1 = glm((claim1==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data,year<1919), family=binomial(logit))
summary(ct1)
ct2 = glm((claim1==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data,year>=1919 & year<2001), family=binomial(logit))
summary(ct2)
ct3 = glm((outstanding.claim.5==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data, year<1919), family=binomial(logit))
summary(ct3)
ct4 = glm((outstanding.claim.5==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data, year>=1919 & year<1996), family=binomial(logit))
summary(ct4)
ct5 = glm((outstanding.claim.10==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data,year < 1919), family=binomial(logit))
summary(ct5)
ct6 = glm((outstanding.claim.10==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data,year >=1919 & year<1991), family=binomial(logit))
summary(ct6)
ct7 = glm((outstanding.claim.20==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data, year <1919), family=binomial(logit))
summary(ct7)
ct8 = glm((outstanding.claim.20==1 & partial==1) ~ agreement + rivals + contlose + conflict, data=subset(data, year >=1919 & year<1981), family=binomial(logit))
summary(ct8)

stargazer(ct1,ct2,ct3,ct4,ct5,ct6,ct7,ct8,title="Logit Models of the Effect of Legalized Territorial Transfers on Claims (New or Continuuing)",style="apsr",dep.var.labels=claims,covariate.labels=cov,column.labels=labels)