#9_2013 update
data <- read.csv("9_2013.csv")

library(Zelig)
library(stargazer)

data$caprat = (data$cap_1/data$cap_2)
data$lead1 = ifelse(data$lead1 > 0, 1, 0)
data$lead1[is.na(data$lead)] = 0
data$lagtc1 = ifelse(data$lagtc1 > 0, 1, 0)
data$lagtc1[is.na(data$lagtc1)] = 0

#Table 1 w/ rivalry added
m1 = glm(lead1 ~ agreement + contlose + conflict + rivals, data=data, family=binomial(logit))
summary(m1)
m2 = glm(lead1 ~ agreement + arbadj2 + conflict + contlose + rivals, data=data, family=binomial(logit))
summary(m2)
m3 = glm(window5 ~ agreement + conflict + contlose + rivals, data=data, family=binomial(logit))
summary(m3)
m4 = glm(window5 ~ agreement + arbadj2 + conflict + contlose + rivals, data=data, family=binomial(logit))
summary(m4)
m5 = glm(window10 ~ agreement + conflict + contlose + rivals, data=data, family=binomial(logit))
summary(m5)
m6 = glm(window10 ~ agreement + arbadj2 + conflict + contlose + rivals, data=data, family=binomial(logit))
summary(m6)
m7 = glm(window20 ~ agreement + contlose + conflict + rivals, data=data, family=binomial(logit))
summary(m7)
m8 = glm(window20 ~ agreement + arbadj2 + contlose + conflict + rivals, data=data, family=binomial(logit))
summary(m8)

library(stargazer)
mids <- c("MID within 1 Year","MID within 5 Years","MID within 10 Years","MID within 20 Years")
cov <- c("Agreement","Adjudication/Arbitration","Conflict","Homeland","Capability Ratio","Rivalry")
stargazer(m1,m2,m3,m4,m5,m6,m7,m8,title="Logit Models of the Effect of Legalized Territorial Transfers on Territorial MIDs",style="apsr",dep.var.labels=mids,covariate.labels=cov)

i1 = glm(lead1 ~ agreement*conflict + contlose + rivals, data=data, family=binomial(logit))
summary(i1)
i2 = glm(window5 ~ agreement*conflict + contlose + rivals, data=data, family=binomial(logit))
summary(i2)
i3 = glm(window10 ~ agreement*conflict + contlose + caprat + rivals, data=data, family=binomial(logit))
summary(i3)
i4 = glm(window20 ~ agreement*conflict + contlose + rivals, data=data, family=binomial(logit))
summary(i4)
i5 = glm(lagtc1 ~ agreement*conflict + contlose + rivals, data=data, family=binomial(logit))
summary(i5)
# i6 = glm(outstanding.claim5 ~ agreement*conflict + contlose + caprat + rivals, data=data, family=binomial(logit))
# summary(i6)

interactions <- c("Agreement","Conflict","Homeland","Capability Ratio","Rivalry","Agreement x Conflict")
int.d <- c("MID within 1 Year","MID within 5 Years","MID within 10 Years","MID within 20 Years","Claim within 1 Year")
stargazer(i1,i2,i3,i4,i5,title="Interactions of Conflict and Agreement",style="apsr",dep.var.labels=int.d,covariate.labels=interactions)

k1 <- glm(lead1 ~ agreement*rivals + contlose, data=data, family=binomial(logit))
summary(k1)
k2 = glm(window5 ~ agreement*rivals + contlose, data=data, family=binomial(logit))
summary(k2)
k3 = glm(window10 ~ agreement*rivals + contlose, data=data, family=binomial(logit))
summary(k3)
k4 = glm(window20 ~ agreement*rivals + contlose, data=data, family=binomial(logit))
summary(k4)
k5 = glm(lagtc1 ~ agreement*rivals + contlose, data=data, family=binomial(logit))
summary(k5)

#predicted probabilities
z1 = zelig(lead1~agreement+contlose+conflict+rivals,data=data,model="logit")
x0 = setx(z1,agreement=0,contlose=1,conflict=0,rivals=0)
s0 = sim(z1,x=x0)
summary(s0)
x1 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=0)
s1 = sim(z1,x=x1)
summary(s1)
# x2 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=0)
# s2 = sim(z1,x=x2)
# summary(s2)
z2 = zelig(window5~agreement+contlose+conflict+rivals,data=data,model="logit")
summary(z2)
x3 = setx(z2,agreement=0,contlose=1,conflict=0,rivals=0)
s3 = sim(z2,x=x3)
summary(s3)
x4 = setx(z2,agreement=1,contlose=1,conflict=0,rivals=0)
s4 = sim(z2,x=x4)
summary(s4)
z3 = zelig(window10~agreement+contlose+conflict+rivals,data=data,model="logit")
x5 = setx(z3,agreement=0,contlose=1,conflict=0,rivals=0)
s5 = sim(z3,x=x5)
summary(s5)
x6 = setx(z3,agreement=1,contlose=1,conflict=0,rivals=0)
s6 = sim(z3,x=x6)
summary(s6)
z4 = zelig(window20~agreement+contlose+conflict+rivals,data=data,model="logit")
x7 = setx(z4,agreement=0,contlose=1,conflict=0,rivals=0)
s7 = sim(z4,x=x7)
summary(s7)
x8 = setx(z4,agreement=1,contlose=1,conflict=0,rivals=0)
s8 = sim(z4,x=x8)
summary(s8)

### do some for rivalry, which is significant at 10 and 20 years
x0.5 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=0)
x1.5 = setx(z1,agreement=1,contlose=1,conflict=0,rivals=1)
r0 = sim(z1,x=x0.5)
summary(r0)
r1 = sim(z1,x=x1.5)
summary(r1)
x2.5 = setx(z2,agreement=1,contlose=1,conflict=0,rivals=0)
x3.5 = setx(z2,agreement=1,contlose=1,conflict=0,rivals=1)
r2 = sim(z2,x=x2.5)
summary(r2)
r3 = sim(z2,x=x3.5)
summary(r3)
x4.5 = setx(z3,agreement=1,contlose=1,conflict=0,rivals=0)
x5.5 = setx(z3,agreement=1,contlose=1,conflict=0,rivals=1)
r4 = sim(z3,x=x4.5)
summary(r4)
r5 = sim(z3,x=x5.5)
summary(r5)
x6.5 = setx(z4,agreement=1,contlose=1,conflict=0,rivals=0)
x7.5 = setx(z4,agreement=1,contlose=1,conflict=0,rivals=1)
r6 = sim(z4,x=x6.5)
summary(r6)
r7 = sim(z4,x=x7.5)
summary(s7)
