m1 = glm(ongoing ~ non.pleb, data=data,family=binomial(logit))
summary(m1)
m2 = glm(ongoing ~ non.pleb + contlose + conflict,data=data,family=binomial(logit))
summary(m2)
m2.1 = glm(ongoing ~ contlose + conflict*non.pleb,data=data,family=binomial(logit))
summary(m2.1)
m3 = glm(ongoing ~ agreement, data=data,family=binomial(logit))
summary(m3)
m4 = glm(ongoing ~ agreement + contlose,data=data,family=binomial(logit))
summary(m4)

m5 = glm(lag(ter, -1) ~ non.pleb, data=data, family=binomial(logit))
summary(m5)
m6 = glm(lag(ter, -1) ~ non.pleb + contlose + conflict, data=data, family=binomial(logit))
summary(m6)
m7 = glm(lag(ter, -1) ~ agreement, data=data, family=binomial(logit))
summary(m7)
m8 = glm(lag(ter, -1) ~ agreement + contlose, data=data, family=binomial(logit))
summary(m8)

#make some latex tables
library(stargazer)
stargazer(m1, m2, m2.1, title="The Effect of Treaties on Territorial Claims", style="apsr")

stargazer(m3, m4, title="The Effect of Non-Violent Agreements on Territorial Claims", style="apsr")

stargazer(m5, m6, m7, m8, title="The Effect of Agreements on Territorial MIDs", style="apsr")



summary(glm(w20 ~ agreement, data=data,family=binomial(logit)))
summary(glm(w10 ~ agreement, data=data,family=binomial(logit)))


############### Rd 2

data$caprat = (data$cap_1/data$cap_2)

m1 = glm(lag(ter, -1) ~ non.pleb, data=data, family=binomial(logit))
summary(m1)
m2 = glm(lag(ter, -1) ~ non.pleb + conflict, data=data, family=binomial(logit))
summary(m2)
m3 = glm(lag(ter, -1) ~ non.pleb*conflict, data=data, family=binomial(logit))
summary(m3)
m4 = glm(lag(ter, -1) ~ non.pleb + conflict + as.numeric(pop), data=data, family=binomial(logit))
summary(m4)
m5 = glm(lag(ter, -1) ~ non.pleb + conflict + as.numeric(pop) + as.numeric(area), data=data, family=binomial(logit))
summary(m5)
m6 = glm(lag(ter, -1) ~ non.pleb + conflict + as.numeric(pop) + as.numeric(area) + contlose, data=data, family=binomial(logit))
summary(m6)
m7 = glm(lag(ter, -1) ~ non.pleb + conflict + as.numeric(pop) + as.numeric(area) + contlose + caprat, data=data, family=binomial(logit))
summary(m7)
m8 = glm(lag(ter, -1) ~ non.pleb + conflict + contlose + caprat, data=data, family=binomial(logit))
summary(m8)

library(stargazer)
stargazer(m1, m2, m3, m4, m5, m6, m7, m8, title="The Effect of Agreements on MIDs", style="apsr")

m9 = glm(lag(ter, -1) ~ arbadj2, data=data, family=binomial(logit))
summary(m9)
m10 = glm(lag(ter, -1) ~ arbadj2 + conflict, data=data, family=binomial(logit))
summary(m10)
m11 = glm(lag(ter, -1) ~ arbadj2*conflict, data=data, family=binomial(logit))
summary(m11)
m12 = glm(lag(ter, -1) ~ arbadj2 + conflict + as.numeric(pop), data=data, family=binomial(logit))
summary(m12)
m13 = glm(lag(ter, -1) ~ arbadj2 + conflict + as.numeric(pop) + as.numeric(area), data=data, family=binomial(logit))
summary(m13)
m14 = glm(lag(ter, -1) ~ arbadj2 + conflict + as.numeric(pop) + as.numeric(area) + contlose, data=data, family=binomial(logit))
summary(m14)
m15 = glm(lag(ter, -1) ~ arbadj2 + conflict + as.numeric(pop) + as.numeric(area) + contlose + caprat, data=data, family=binomial(logit))
summary(m15)
m16 = glm(lag(ter, -1) ~ arbadj2 + conflict + contlose + caprat, data=data, family=binomial(logit))
summary(m16)

stargazer(m9, m10, m11, m12, m13, m14, m15, m16, title="The Effect of Adjudication/Arbitration on MIDs", style="apsr")

m17 = glm(lag(ter, -1) ~ non.pleb + arbadj2, data=data, family=binomial(logit))
summary(m17)
m18 = glm(lag(ter, -1) ~ non.pleb + arbadj2 + conflict, data=data, family=binomial(logit))
summary(m18)
m19 = glm(lag(ter, -1) ~ non.pleb + arbadj2*conflict, data=data, family=binomial(logit))
summary(m19)
m20 = glm(lag(ter, -1) ~ non.pleb + arbadj2 + conflict + as.numeric(pop), data=data, family=binomial(logit))
summary(m20)
m21 = glm(lag(ter, -1) ~ non.pleb + arbadj2 + conflict + as.numeric(pop) + as.numeric(area), data=data, family=binomial(logit))
summary(m21)
m22 = glm(lag(ter, -1) ~ non.pleb + arbadj2 + conflict + as.numeric(pop) + as.numeric(area) + contlose, data=data, family=binomial(logit))
summary(m22)
m23 = glm(lag(ter, -1) ~ non.pleb + arbadj2 + conflict + as.numeric(pop) + as.numeric(area) + contlose + caprat, data=data, family=binomial(logit))
summary(m23)
m24 = glm(lag(ter, -1) ~ non.pleb + arbadj2 + conflict + contlose + caprat, data=data, family=binomial(logit))
summary(m24)
m25 = glm(lag(ter, -1) ~ non.pleb*arbadj2 + conflict + caprat + contlose, data=data, family=binomial(logit))
summary(m25)

stargazer(m17,m18,m19,m20,m21,m22,m23,m24,m25,title="Additive and Interactive Effects of Agreements and Ajudication",style="apsr")